site_name: Evolutionary OpenRLHF
docs_dir: "."
site_description: 进化强化学习框架 - 基于OpenRLHF的种群进化训练
repo_url: https://github.com/privacynot/evolutionary-openrlhf   # 替换为你的实际地址
repo_name: evolutionary-openrlhf

theme:
  name: material

nav:
  - 首页: index.md
  - 入门指南:
      - 项目简介1: project-overview1.md
      - 项目简介2: project-overview2.md
      - 快速开始: quickstart.md
      - 配置系统: configuration.md
  - 核心概念:
      - 算法主流程: algorithm.md
      - 核心数据结构: data-structures.md
  - 模块接口: api-reference.md
  - 开发扩展: development.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
